CREATE DATABASE DBShop;
USE DBShop;

CREATE TABLE Products (
    ID INT AUTO_INCREMENT,
    Name VARCHAR(50),
    Description VARCHAR(100),
    Price VARCHAR(50),
    WareHouseAmount INT,
    PRIMARY KEY (ID)
);

CREATE TABLE Customers (
    ID INT AUTO_INCREMENT,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    EMail VARCHAR(100),
    Address VARCHAR(100),
    PRIMARY KEY (ID)
);

CREATE TABLE Orders (
   ID INT AUTO_INCREMENT,
   CustomerID INT,
   FOREIGN KEY (CustomerID) REFERENCES Customers(ID) ON DELETE NO ACTION,
   Date DATE,
   PRIMARY KEY (ID)
);

CREATE TABLE OrderItems (
    ID INT AUTO_INCREMENT,
    OrderID INT,
    FOREIGN KEY (OrderID) REFERENCES Orders(ID) ON DELETE NO ACTION,
    ProductID INT,
    FOREIGN KEY (ProductID) REFERENCES Products(ID) ON DELETE NO ACTION,
    PRIMARY KEY (ID)
);